# Generated by Django 3.2.5 on 2022-01-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
